### ISSUE TITLE
JWE decryption error

### ISSUE THREAD

**Issue by Manduri** [DinoChiesa/ApigeeEdge-CustomPolicy-EncryptedJWT#1]
Hello Dino,
I am trying to perform encryption and decryption on JSON payload where I am able to encrypt required payload using JWE(/generate_jwe) but facing below error while trying to verify (/verify_jwe)

Looks like it is due to padding(RSA-OAEP-256), can we use different padding?

Please suggest

com.nimbusds.jose.JOSEException: Decryption error at com.nimbusds.jose.crypto.impl.RSA_OAEP_256.decryptCEK(RSA_OAEP_256.java:123) at com.nimbusds.jose.crypto.RSADecrypter.decrypt(RSADecrypter.java:278) at com.nimbusds.jose.JWEObject.decrypt(JWEObject.java:415) at com.google.apigee.edgecallouts.VerifyJwe.decrypt(VerifyJwe.java:52) at com.google.apigee.edgecallouts.VerifyBase.execute(VerifyBase.java:93) at com.apigee.steps.javacallout.JavaCalloutStepDefinition$ClassLoadWrappedExecution.execute(JavaCalloutStepDefinition.java:235) at com.apigee.steps.javacallout.JavaCalloutStepDefinition$SecurityWrappedExecution$1.run(JavaCalloutStepDefinition.java:302) at com.apigee.steps.javacallout.JavaCalloutStepDefinition$SecurityWrappedExecution$1.run(JavaCalloutStepDefinition.java:300) at java.security.AccessController.doPrivileged(Native Method) at com.apigee.steps.javacallout.JavaCalloutStepDefinition$SecurityWrappedExecution.execute(JavaCalloutStepDefinition.java:300) at com.apigee.steps.javacallout.JavaCalloutStepDefinition$CallOutWrapper.execute(JavaCalloutStepDefinition.java:169) at com.apigee.messaging.runtime.steps.StepExecution.execute(StepExecution.java:157) at com.apigee.flow.execution.AbstractAsyncExecutionStrategy$AsyncExecutionTask.call(AbstractAsyncExecutionStrategy.java:82) at com.apigee.flow.execution.AbstractAsyncExecutionStrategy$AsyncExecutionTask.call(AbstractAsyncExecutionStrategy.java:48) at com.apigee.threadpool.CallableWrapperForMDCPreservation.call(CallableWrapperForMDCPreservation.java:26) at com.apigee.threadpool.ThreadPoolManager$QueueAwareCallableTask.call(ThreadPoolManager.java:546) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) Caused by: javax.crypto.BadPaddingException: Decryption error at sun.security.rsa.RSAPadding.unpadOAEP(RSAPadding.java:499) at sun.security.rsa.RSAPadding.unpad(RSAPadding.java:293) at com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:363) at com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:389) at javax.crypto.Cipher.doFinal(Cipher.java:2165) at com.nimbusds.jose.crypto.impl.RSA_OAEP_256.decryptCEK(RSA_OAEP_256.java:115) ... 21 more
--

**Comment by DinoChiesa** [comment]
Hi Mani

Is this reproducible?

Can you give me an example proxy and some requests to send, that reliably
reproduces this behavior?

**Comment by Manduri** [comment]
[apiproxyJWT_rev1_2020_10_05.zip](https://github.com/DinoChiesa/ApigeeEdge-CustomPolicy-EncryptedJWT/files/5328477/apiproxyJWT_rev1_2020_10_05.zip)

**Comment by DinoChiesa** [comment]
Hi Mani, 
The error was in the example bundle. 
The `/generate_jwe` endpoint used a public key that did not match the private key used in the `/verify_jwe` endpoint. 

I have now corrected the examples. Specifically, I updated the policy `Java-VerifyJWE` so that the configuration is now:
```xml
<JavaCallout name="Java-VerifyJWE">
  <Properties>
    <Property name='key-encryption'>RSA-OAEP-256</Property>
    <Property name='debug'>true</Property>
    <Property name='source'>request.formparam.JWE</Property>
    <Property name='private-key'>{private.my_private_key}</Property> <!-- attention -->
  </Properties>
  <ClassName>com.google.apigee.edgecallouts.VerifyJwe</ClassName>
  <ResourceURL>java://apigee-callout-encrypted-jwt-20201116.jar</ResourceURL>
</JavaCallout>
```

Also I provided a README describing how to use the example bundle. 

Please try it. 

Thanks for reporting this.
